name: Backup Railway Postgres

on:
  schedule:
    - cron: '0 2 * * *'   # Daily 02:00 UTC (10:00 AM HKT)
  workflow_dispatch:      # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump database
        id: dump
        env:
          DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
        run: |
          ts=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          outfile="railway-backup-${ts}.dump"
          pg_dump "$DATABASE_URL" \
            --format=custom \
            --no-owner \
            --no-privileges \
            --file="$outfile"
          gzip "$outfile"
          echo "backup_path=${outfile}.gz" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: railway-postgres-${{ github.run_id }}
           path: ${{ steps.dump.outputs.backup_path }}
           retention-days: 30   # Keep backups for 30 days

