 name: Daily Partner Reminders

  on:
    # Run daily at 1 AM UTC (9 AM Hong Kong Time)
    schedule:
      - cron: '0 1 * * *'

    # Allow manual trigger for testing
    workflow_dispatch:

  jobs:
    send-reminders:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            cache-dependency-path: backend/package-lock.json

        - name: Install dependencies
          working-directory: ./backend
          run: npm ci

        - name: Generate Prisma Client
          working-directory: ./backend
          run: npx prisma generate
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        - name: Send Partner Reminders
          working-directory: ./backend
          run: npm run send:reminders
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
            EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
            FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
            ENABLE_PROJECT_REMINDERS: ${{ secrets.ENABLE_PROJECT_REMINDERS }}
            EMAIL_TEST_MODE: ${{ secrets.EMAIL_TEST_MODE }}
            EMAIL_TEST_RECIPIENT: ${{ secrets.EMAIL_TEST_RECIPIENT }}
            LOG_EMAIL_PAYLOADS: ${{ secrets.LOG_EMAIL_PAYLOADS }}
            NODE_ENV: production
